<a href="https://colab.research.google.com/github/Shoaib-Siddiq/L/blob/main/Day_2_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define your matrices as NumPy arrays
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix_b = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Perform matrix multiplication using the @ operator (recommended for clarity)
result = matrix_a @ matrix_b

# Or, using np.dot()
# result = np.dot(matrix_a, matrix_b)

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nResult of Matrix A @ Matrix B:")
print(result)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix A @ Matrix B:
[[ 58  64]
 [139 154]]


In [ ]:
import numpy as np

# Sample dataset
data = np.array([15, 25, 35, 45, 55])

# Min-Max Scaling: rescales data to [0,1]
def min_max_scaling(x):
    return (x - np.min(x)) / (np.max(x) - np.min(x))

# Standardization: zero mean and unit variance
def standardize(x):
    return (x - np.mean(x)) / np.std(x)

scaled_data = min_max_scaling(data)
standardized_data = standardize(data)

print("Original data:", data)
print("Min-Max Scaled data:", scaled_data)
print("Standardized data:", standardized_data)

Original data: [15 25 35 45 55]
Min-Max Scaled data: [0.   0.25 0.5  0.75 1.  ]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
